### ISSUE TITLE
docker-buildx / docker-compose builds failing 

### ISSUE THREAD

**Issue by jmwill86** [shuttle-hq/shuttle#233]
The [new changes](https://github.com/shuttle-hq/shuttle/commit/9d289245789fbbeeb8ac171ace71b9245d900a35) for local deployments and local setup are failing for me with some missing ENV variables and provisioner connection problems it seems?

`docker compose -f docker-compose.dev.yml up --build` output:

```
shuttle-jw-db-1           | 2022-06-30 22:58:08.898 UTC [1] LOG:  database system is ready to accept connections
shuttle-jw-backend-1      | thread 'main' panicked at 'failed to connect to provisioner: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })))', api/src/deployment.rs:380:14
shuttle-jw-backend-1      | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
shuttle-jw-backend-1 exited with code 101
shuttle-jw-provisioner-1  | Error: Format string '/usr/bin/wait-for-pg-then /usr/local/bin/shuttle-provisioner --ip 0.0.0.0 --port %(ENV_PORT)s --shared-pg-uri %(ENV_PG_URI)s' for 'program:shuttle-provisioner.command' contains names ('ENV_PORT') which cannot be expanded. Available names: ENV_CARGO_HOME, ENV_HOME, ENV_HOSTNAME, ENV_PATH, ENV_PG_CLUSTER_NAME, ENV_PG_DATA, ENV_PG_HOST, ENV_PG_LOG, ENV_PG_PASSWORD, ENV_PG_PORT, ENV_PG_URI, ENV_PG_VERSION, ENV_PWD, ENV_RUSTUP_HOME, ENV_RUST_LOG, ENV_RUST_VERSION, ENV_SHLVL, group_name, here, host_node_name, process_num, program_name in section 'program:shuttle-provisioner' (file: '/usr/share/supervisord/supervisord.conf')
shuttle-jw-provisioner-1  | For help, use /usr/bin/supervisord -h
shuttle-jw-provisioner-1 exited with code 2
shuttle-jw-backend-1      | thread 'main' panicked at 'failed to connect to provisioner: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })))', api/src/deployment.rs:380:14
shuttle-jw-backend-1      | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
shuttle-jw-backend-1 exited with code 101
shuttle-jw-backend-1      | thread 'main' panicked at 'failed to connect to provisioner: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })))', api/src/deployment.rs:380:14
shuttle-jw-backend-1      | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
shuttle-jw-backend-1 exited with code 101
shuttle-jw-backend-1      | thread 'main' panicked at 'failed to connect to provisioner: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })))', api/src/deployment.rs:380:14
shuttle-jw-backend-1      | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
shuttle-jw-backend-1 exited with code 101
```

There's also a 'No such file or directory' error on build, changing `/usr/local/bin/service` to `/usr/local/bin/shuttle-backend` in the [dev docker-compose.yml](https://github.com/shuttle-hq/shuttle/blob/main/docker-compose.dev.yml#L28) seem to fix this though.

**Comment by brokad** [comment]
Have you rebuilt the images [as in the README](https://github.com/shuttle-hq/shuttle#working-on-shuttle) by any chance? It looks like your `provisioner` image is still using `supervisord`, which got removed for images built from this commit.

**Comment by jmwill86** [comment]
Yeah I think you're right. Here's my list of images, so the recent/new ones are there but not being used. I'm conscious other users might hit the same problem potentially at some point, even if it might work by deleting the old images? `--pull` and `--no-cache` have no effect, and removing the containers completely didn't help either.

```
public.ecr.aws/j5v8s8v8/backend       latest    3677301d419c   2 hours ago   1.76GB
public.ecr.aws/j5v8s8v8/provisioner   latest    3dfe3335b410   2 hours ago   1.65GB
<none>                                <none>    5236c1675013   3 hours ago   1.65GB
<none>                                <none>    c0d6afb9aedb   3 hours ago   1.76GB
postgres                              latest    b2261d3c6ce0   8 days ago    376MB
public.ecr.aws/shuttle/backend        latest    f0cff2aefda6   3 weeks ago   1.91GB
public.ecr.aws/shuttle/provisioner    latest    6f9699bdadc3   3 weeks ago   1.89GB
```

However... changing `CONTAINER_REGISTRY=public.ecr.aws/shuttle` to `CONTAINER_REGISTRY=public.ecr.aws/j5v8s8v8` in .env seems to fix the issue.

Happy to do a merge request for this change if it helps, I'm not sure if it's best to change docker-bake.hcl to match .env file though, or the reverse? If they always need to match then it should probably be a variable instead even?

**Comment by chesedo** [comment]
> I'm not sure if it's best to change docker-bake.hcl to match .env file though

Rather change the `docker-bake.hcl` with the friendly name :smile:
