### ISSUE TITLE
[Bug]: Local development not closes the app properly with Actix and Static folders

### ISSUE THREAD

**Issue by piny4man** [shuttle-hq/shuttle#809]
### What happened?

After stopping my local API process, hitting Ctrl+C an error occurred. After that, I can't start the local environment using the same port. Also, I am not able to stop it on my system. Here are the errors.

```bash
cargo shuttle run
    Building /home/piny4man/DEV/github/power-scouter
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/piny4man/DEV/github/power-scouter/front/Cargo.toml
workspace: /home/piny4man/DEV/github/power-scouter/Cargo.toml
   Compiling prost-build v0.11.8
   Compiling rustix v0.36.11
warning: value assigned to `coeff` is never read
  --> shared/src/helpers/calculations.rs:13:13
   |
13 |     let mut coeff: [f64; 3] = [0.0, 0.0, 0.0];
   |             ^^^^^
   |
   = help: maybe it is overwritten before being read?
   = note: `#[warn(unused_assignments)]` on by default


warning: value assigned to `coeff` is never read
  --> shared/src/helpers/calculations.rs:62:13
   |
62 |     let mut coeff: [f64; 4] = [0.0, 0.0, 0.0, 0.0];
   |             ^^^^^
   |
   = help: maybe it is overwritten before being read?


warning: 2 warnings emitted


   Compiling tonic-build v0.8.4
   Compiling is-terminal v0.4.5
   Compiling clap v4.1.11
   Compiling opentelemetry-proto v0.1.0
   Compiling opentelemetry-otlp v0.11.0
   Compiling shuttle-common v0.14.0
   Compiling shuttle-service v0.14.0
   Compiling shuttle-proto v0.14.0
   Compiling shuttle-static-folder v0.14.0
   Compiling shuttle-runtime v0.14.0
   Compiling shuttle-actix-web v0.14.0
   Compiling power-scouter v0.2.0 (/home/piny4man/DEV/github/power-scouter)
    Finished dev [unoptimized + debuginfo] target(s) in 10.97s
These static folders can be accessed by power-scouter
╭─────────╮
│ Folders │
╞═════════╡
│ static  │
╰─────────╯

    Starting power-scouter on http://127.0.0.1:8000

2023-04-20T19:01:03.986947180Z  INFO actix_server::builder: starting 4 workers
2023-04-20T19:01:03.986994790Z  INFO actix_server::server: Tokio runtime found; starting in existing Tokio runtime
^C
```
This is the error just after the process should be stopped.
```bash
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError((End, ""))', /home/piny4man/.cargo/registry/src/github.com-1ecc6299db9ec823/shuttle-runtime-0.14.0/src/alpha/mod.rs:323:79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Version

v0.14.0

### Which operating systems are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Relevant log output

```sh
cargo shuttle run
    Building /home/piny4man/DEV/github/power-scouter
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/piny4man/DEV/github/power-scouter/front/Cargo.toml
workspace: /home/piny4man/DEV/github/power-scouter/Cargo.toml
   Compiling prost-build v0.11.8
   Compiling rustix v0.36.11
warning: value assigned to `coeff` is never read
  --> shared/src/helpers/calculations.rs:13:13
   |
13 |     let mut coeff: [f64; 3] = [0.0, 0.0, 0.0];
   |             ^^^^^
   |
   = help: maybe it is overwritten before being read?
   = note: `#[warn(unused_assignments)]` on by default


warning: value assigned to `coeff` is never read
  --> shared/src/helpers/calculations.rs:62:13
   |
62 |     let mut coeff: [f64; 4] = [0.0, 0.0, 0.0, 0.0];
   |             ^^^^^
   |
   = help: maybe it is overwritten before being read?


warning: 2 warnings emitted


   Compiling tonic-build v0.8.4
   Compiling is-terminal v0.4.5
   Compiling clap v4.1.11
   Compiling opentelemetry-proto v0.1.0
   Compiling opentelemetry-otlp v0.11.0
   Compiling shuttle-common v0.14.0
   Compiling shuttle-service v0.14.0
   Compiling shuttle-proto v0.14.0
   Compiling shuttle-static-folder v0.14.0
   Compiling shuttle-runtime v0.14.0
   Compiling shuttle-actix-web v0.14.0
   Compiling power-scouter v0.2.0 (/home/piny4man/DEV/github/power-scouter)
    Finished dev [unoptimized + debuginfo] target(s) in 10.97s
These static folders can be accessed by power-scouter
╭─────────╮
│ Folders │
╞═════════╡
│ static  │
╰─────────╯

    Starting power-scouter on http://127.0.0.1:8000

2023-04-20T19:01:03.986947180Z  INFO actix_server::builder: starting 4 workers
2023-04-20T19:01:03.986994790Z  INFO actix_server::server: Tokio runtime found; starting in existing Tokio runtime
^C

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError((End, ""))', /home/piny4man/.cargo/registry/src/github.com-1ecc6299db9ec823/shuttle-runtime-0.14.0/src/alpha/mod.rs:323:79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by oddgrd** [comment]
Hey! We are working on resolving this bug, and [the fix](https://github.com/shuttle-hq/shuttle/pull/805) should be included in a release early next week. We forgot to open an issue for this bug ourselves, sorry about that!

**Comment by piny4man** [comment]
Thanks @oddgrd !
