### ISSUE TITLE
[Bug]: `cargo shuttle run` error for `examples/next/hello-world`

### ISSUE THREAD

**Issue by paulotten** [shuttle-hq/shuttle#997]
### What happened?

Running `cargo shuttle run` in the `examples/next/hello-world` directory I got the following error:

```
    Finished dev [unoptimized + debuginfo] target(s) in 28.93s
Installing shuttle-next runtime. This can take a while...
thread 'main' panicked at 'shuttle-runtime version should be in the `name version` format', cargo-shuttle/src/lib.rs:1296:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The matching code is here: https://github.com/shuttle-hq/shuttle/blob/main/cargo-shuttle/src/lib.rs#L1296

Investigating I found that `stdout` (line 1288) was and empty string. Adding code to check `stderr`, I found it to read:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedArgument { arg: "--version" }', runtime/src/bin/shuttle-next.rs:14:34
```

Looking at https://github.com/shuttle-hq/shuttle/blob/main/runtime/src/next/args.rs I didn't see a `version` option.

Checking the git history for the file I see https://github.com/shuttle-hq/shuttle/commit/5f0874c966a6ec9b5b9c9a0f3ca1ed90e56460ca#diff-651941ab3b205fa0a1385341412700b34be3a850f36cf002fe60810f4ba89e2aL4, which seems to remove the option.

### Version

head

### Which operating system(s) are you seeing the problem on?

Linux

### Which CPU architectures are you seeing the problem on?

x86_64

### Duplicate declaration

- [X] I have searched the issues and there are none like this.

**Comment by paulotten** [comment]
The `args` crate, which was used to replace `clap` doesn't appear to have a version option built in.
